more aliasses

diff --git a/shell/aliasrc b/shell/aliasrc
--- a/shell/aliasrc
+++ b/shell/aliasrc
@@ -13,7 +13,7 @@ alias \
 
 # Colorize commands when possible.
 alias \
-	ls="ls -AhNF --color=auto --group-directories-first" \
+	l="ls -ahNF --color=auto --group-directories-first" \
 	grep="grep --color=auto" \
 	diff="diff --color=auto" \
 	ccat="highlight --out-format=ansi"
@@ -26,8 +26,10 @@ alias \
 	sdn="sudo shutdown -h now" \
 	f="$FILE" \
 	e="$EDITOR" \
+	n="ncdu" \
 	smi="sudo make install" \
 	t="tldr" \
+	ts="tldr -s" \
 	wp="setbg ~/Downloads/Wallpapers/wp" \
 	z="zathura"
 
@@ -40,13 +42,28 @@ alias \
 	p="sudo pacman" \
 	y="yay" \
 	psyu='sudo pacman -Syu' \
-	yi="yay -Qiv" \
+	yi="yay -Qi" \
+	ye="yay -Qe" \
 	ysua="yay -Sua --noconfirm" \
 	ysyu="yay -Syu --noconfirm" \
 	yr="yay -Rnsu" \
 	unlock="sudo rm /var/lib/pacman/db.lck" \
 	cleanup='sudo pacman -Rnsu $(pacman -Qtdq)' \
 	mirror="sudo reflector -f 30 -l 30 --number 10 --save /etc/pacman.d/mirrorlist"
+
+ # get top process eating memory / cpu if not work try excute : export LC_ALL='C'
+alias \
+	psmem='ps -e -orss=,args= | sort -b -k1 -nr' \
+	psmem10='ps -e -orss=,args= | sort -b -k1 -nr | head -10' \
+	pscpu='ps -e -o pcpu,cpu,nice,state,cputime,args|sort -k1,1n -nr' \
+	pscpu10='ps -e -o pcpu,cpu,nice,state,cputime,args|sort -k1,1n -nr | head -10'
+
+ # History
+alias \
+	h='history' \
+	hs='history | grep' \
+	hsi='history | grep -i' \
+	hist10='print -l ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
 
 # youtube-dl
 alias \
@@ -89,7 +106,7 @@ alias \
  	 g='git' \
 	 gin="git init" \
 	 gs='git status -sb' \
-	 gc='git commit' \
+	 gc='git commit -v' \
 	 gcf='git config --global' \
 	 ga='git add .' \
 	 gpl='git pull' \
@@ -97,11 +114,13 @@ alias \
 	 gpu='git push' \
 	 gpuom='git push -u origin master' \
 	 gd='git diff' \
+	 gds='git diff --staged' \
 	 gcm='git checkout master' \
 	 gnb='git checkout -b' \
 	 gac='git add . && git commit' \
 	 grs='git restore --staged .' \
 	 gre='git restore' \
+	 grss='git restore --source' \
 	 gr='git remote' \
 	 gcl='git clone' \
 	 gcle='git clean -fdi' \
@@ -117,3 +136,86 @@ alias \
 	 gf="git fetch origin" \
 	 grf="git reflog" \
 	 grh="git reset HEAD~"
+
+ # FUNCTION
+ alias x=extract \
+
+ extract() {
+	local remove_archive
+	local success
+	local extract_dir
+
+	if (( $# == 0 )); then
+		cat <<-'EOF' >&2
+			Usage: extract [-option] [file ...]
+			Options:
+			    -r, --remove    Remove archive after unpacking.
+		EOF
+	fi
+
+	remove_archive=1
+	if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+		remove_archive=0
+		shift
+	fi
+
+	while (( $# > 0 )); do
+		if [[ ! -f "$1" ]]; then
+			echo "extract: '$1' is not a valid file" >&2
+			shift
+			continue
+		fi
+
+		success=0
+		extract_dir="${1:t:r}"
+		case "${1:l}" in
+			(*.tar.gz|*.tgz) (( $+commands[pigz] )) && { pigz -dc "$1" | tar xv } || tar zxvf "$1" ;;
+			(*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+			(*.tar.xz|*.txz)
+				tar --xz --help &> /dev/null \
+				&& tar --xz -xvf "$1" \
+				|| xzcat "$1" | tar xvf - ;;
+			(*.tar.zma|*.tlz)
+				tar --lzma --help &> /dev/null \
+				&& tar --lzma -xvf "$1" \
+				|| lzcat "$1" | tar xvf - ;;
+			(*.tar.zst|*.tzst)
+				tar --zstd --help &> /dev/null \
+				&& tar --zstd -xvf "$1" \
+				|| zstdcat "$1" | tar xvf - ;;
+			(*.tar) tar xvf "$1" ;;
+			(*.tar.lz) (( $+commands[lzip] )) && tar xvf "$1" ;;
+			(*.tar.lz4) lz4 -c -d "$1" | tar xvf - ;;
+			(*.tar.lrz) (( $+commands[lrzuntar] )) && lrzuntar "$1" ;;
+			(*.gz) (( $+commands[pigz] )) && pigz -dk "$1" || gunzip -k "$1" ;;
+			(*.bz2) bunzip2 "$1" ;;
+			(*.xz) unxz "$1" ;;
+			(*.lrz) (( $+commands[lrunzip] )) && lrunzip "$1" ;;
+			(*.lz4) lz4 -d "$1" ;;
+			(*.lzma) unlzma "$1" ;;
+			(*.z) uncompress "$1" ;;
+			(*.zip|*.war|*.jar|*.sublime-package|*.ipa|*.ipsw|*.xpi|*.apk|*.aar|*.whl) unzip "$1" -d $extract_dir ;;
+			(*.rar) unrar x -ad "$1" ;;
+			(*.rpm) mkdir "$extract_dir" && cd "$extract_dir" && rpm2cpio "../$1" | cpio --quiet -id && cd .. ;;
+			(*.7z) 7za x "$1" ;;
+			(*.deb)
+				mkdir -p "$extract_dir/control"
+				mkdir -p "$extract_dir/data"
+				cd "$extract_dir"; ar vx "../${1}" > /dev/null
+				cd control; tar xzvf ../control.tar.gz
+				cd ../data; extract ../data.tar.*
+				cd ..; rm *.tar.* debian-binary
+				cd ..
+			;;
+			(*.zst) unzstd "$1" ;;
+			(*)
+				echo "extract: '$1' cannot be extracted" >&2
+				success=1
+			;;
+		esac
+
+		(( success = $success > 0 ? $success : $? ))
+		(( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+		shift
+	done
+}
